name = "streamsphere-worker"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "streamsphere-db"
database_id = "75d0350d-d33a-4a0d-a108-477acfd94054"

[ai]
binding = "AI"

[pages]
pages_build_output_dir = "frontend"